[pontos-release] Remove project parameter, f-string-ed strings, refactor
greenbone/pontos pull request #105
Opened 2021-06-06 09:59 UTC by y0urself

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/pontos/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

2021-06-06 17:23 UTC, bjoernricks requested changes

2021-06-06 17:23 UTC, bjoernricks commented on pontos/release/helper.py
> +    stream = popen('basename -s .git `git config --get remote.origin.url`')
* We should use subprocess instead of popen.
* The name of the project should be *calculated* using the path module
  name = Path(<git remote url>).name
  project = Path(name).stem
* I really think using a remote uri is not 100% reliable. The remote can point to whatever you want
* So maybe we just keep the project flag and use the calculation if it is not set

2021-06-06 17:23 UTC, bjoernricks commented on pontos/release/helper.py
> +    executed, filename = _version.main(False, args=args)
I would recommend to only pass boolean args by keyword.

2021-06-07 10:30 UTC, y0urself commented on pontos/release/helper.py
> +    stream = popen('basename -s .git `git config --get remote.origin.url`')
it will not work with Path() if the remote origin url is ssh.

2021-06-07 10:31 UTC, y0urself commented on pontos/release/helper.py
> +    executed, filename = _version.main(False, args=args)
The called main looks like this:
`def main(leave=True, args=None):`
So i can not pass any parameter but `leave` and `args`...

2021-06-08 06:10 UTC, bjoernricks commented on pontos/release/helper.py
> +    executed, filename = _version.main(False, args=args)
For the readability it is always better to pass pass booleans as keywords. `somefunc(True, False, True)` is not readable. In our case `version.main(leave=False, args=args)` is easier to read.

2021-06-08 06:10 UTC, bjoernricks commented on pontos/release/helper.py
> +    executed, filename = _version.main(False, args=args)
```suggestion
    executed, filename = _version.main(leave=False, args=args)
```

2021-06-08 06:14 UTC, bjoernricks approved these changes

2021-06-08 06:14 UTC, merged