Add pontos-update-header option to ignore files
greenbone/pontos pull request #144
Opened 2021-06-24 12:30 UTC by timopollmeier

**What**:
The script can be passed a file path or check the directory given with
the --directory option for a .pontos-header-ignore file.
All files matching the paths or globs listed in this filed will be
skipped when adding or updating the headers.

**Why**:
To allow skipping build directories and other files that should not have a header.

**How**:
By running the script on a directory with a .pontos-header-ignore file
that has both a normal path and a recursive glob.

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/pontos/blob/master/CHANGELOG.md) Entry
- [ ] Documentation

2021-06-29 06:37 UTC, y0urself approved these changes

2021-06-29 06:37 UTC, y0urself commented on pontos/updateheader/updateheader.py
> +                print(f"{file}: Matches exclusion list.")
```suggestion
                print(f"{file}: Ignoring file from exclusion list.")
```
```suggestion
                print(f"{file}: Matches exclusion list.")
```

2021-06-29 10:38 UTC, bjoernricks requested changes

2021-06-29 10:38 UTC, bjoernricks commented on pontos/updateheader/updateheader.py
> +    ]
Please don't use os.path anymore. All code must use pathlib now. pathlib is much easier to handle.

2021-06-29 10:38 UTC, bjoernricks commented on pontos/updateheader/updateheader.py
> +            exclude_file = open(path, "r")
open should never be used without a with statement. Here either [Path.open](https://docs.python.org/3/library/pathlib.html#pathlib.Path.open) or [Path.read_text](https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_text) should be used.

2021-06-29 10:45 UTC, y0urself commented on pontos/updateheader/updateheader.py
> +        path = os.path.join(directory, ".pontos-header-ignore")
```suggestion
        path = Path(directory) / ".pontos-header-ignore"
```

2021-07-02 11:19 UTC, bjoernricks approved these changes

2021-07-02 11:19 UTC, merged