Refactor: Exclude `shell_command_runner` from arguments
greenbone/pontos pull request #323
Opened 2022-05-13 09:46 UTC by y0urself

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] Conventional commit message
- [ ] Documentation

2022-05-13 18:55 UTC, Dexus approved these changes

2022-05-16 10:15 UTC, bjoernricks requested changes

2022-05-17 05:07 UTC, y0urself commented on pontos/release/release.py
> +        shell_cmd_runner=shell_cmd_runner,
yes. But I would suppose, that another PR would be more fitting for this, because this again changes a lot of code and tests. (New mocks, etc. ...)

2022-05-17 07:03 UTC, bjoernricks approved these changes

2022-05-17 07:05 UTC, merged