Refactor: Introduce Mixins for GitHubRESTApi
greenbone/pontos pull request #418
Opened 2022-09-22 20:03 UTC by y0urself

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] Conventional commit message
- [ ] Documentation

2022-09-23 06:06 UTC, bjoernricks requested changes
My idea was to split the things into several sub classes for an api like `api.artifact.get_repository_artifacts("foo/bar")` similar like https://github.com/octokit/octokit.js#octokitrest-endpoint-methods

2022-09-23 06:06 UTC, bjoernricks commented on pontos/github/api/api.py
> +class FileStatus(Enum):
Needs to be imported into the `__init__.py` module because it should be a public API to be used as from pontos.github.api import FileStatus.

2022-09-23 06:06 UTC, bjoernricks commented on pontos/github/api/api.py
> +DEFAULT_TIMEOUT_CONFIG = httpx.Timeout(180.0)  # three minutes
Needs to be imported into the `__init__.py` module because it should be a public API.

2022-09-23 06:06 UTC, bjoernricks commented on pontos/github/argparser.py
> +from pontos.github.api.api import FileStatus
Should stay as it is.

2022-09-23 06:06 UTC, bjoernricks commented on tests/github/test_argparser.py
> +from pontos.github.api.api import FileStatus
Should stay as it is.

2022-09-23 06:06 UTC, bjoernricks commented on tests/github/test_cmds.py
> +from pontos.github.api.api import FileStatus
Should stay as it is.

2022-09-23 06:06 UTC, bjoernricks commented on tests/release/test_release.py
> +    @patch("pontos.github.api.release.httpx", spec=httpx)
That looks very ugly :-(

2022-09-26 08:52 UTC, y0urself commented on tests/release/test_release.py
> +    @patch("pontos.github.api.release.httpx", spec=httpx)
We may leave it the way it is until further refactoring?

2022-09-26 09:06 UTC, bjoernricks approved these changes

2022-09-26 09:13 UTC, merged