Pholthaus/GitHub create release
greenbone/pontos pull request #452
Opened 2022-10-13 02:49 UTC by pascalholthaus

**What**:
Add cmd option to create a github release to pontos-github.

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] Conventional commit message
- [ ] Documentation

2022-10-14 05:46 UTC, bjoernricks commented on pontos/git/git.py
> +        exec_git(*args, cwd=self._cwd)
Not sure if a push_tag method is really necessary imho a normal push would fit here too
```
def push(refs: Iterable[str], remote: Optional[str] = None) -> None:
    args = ["push"]
    if remote:
        args.append(remote)
   args.extend(refs)
   exec_git(*args, cwd=self._cwd)
```

2022-10-14 05:47 UTC, bjoernricks commented on pontos/github/api/release.py
> +    def create_github_tag(
IMHO github is superfluous here because the class is already named after GitHub
```suggestion
    def create_tag(
```

2022-10-14 05:53 UTC, bjoernricks commented on pontos/github/api/release.py
> +        date: str = str(datetime.now().isoformat()),
IMHO this could possibly lead to a bug because as far as I remember the date variable becomes a member of the class method and is therefore already initialized when the module of the class is imported.

quick example
```python
>>> def foo(a = (lambda: print("i am called already"))()):
...     pass
... 
i am called already
```

2022-10-14 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +        date: str = str(datetime.now().isoformat()),
You should init it to None and add a if date is None: date = ... code path within the method.

2022-10-14 05:55 UTC, bjoernricks commented on pontos/github/api/release.py
> +    def create_github_tag_reference(
```suggestion
    def create_tag_reference(
```

2022-10-16 23:40 UTC, pascalholthaus commented on pontos/git/git.py
> +        exec_git(*args, cwd=self._cwd)
Removed

2022-10-16 23:40 UTC, pascalholthaus commented on pontos/github/api/release.py
> +    def create_github_tag(
changed

2022-10-16 23:41 UTC, pascalholthaus commented on pontos/github/api/release.py
> +    def create_github_tag_reference(
changed

2022-10-16 23:41 UTC, pascalholthaus commented on pontos/github/api/release.py
> +        date: str = str(datetime.now().isoformat()),
Done, Thanks!!

2022-10-17 05:54 UTC, bjoernricks requested changes

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +        gobject: str,
```suggestion
        git_object: str,
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +        otype: str = "commit",
```suggestion
        git_object_type: str = "commit",
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +        date: str = None,
```suggestion
        date: Optional[str] = None,
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +            gobject: The SHA of the git object this is tagging.
```suggestion
            git_object: The SHA of the git object this is tagging.
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/api/release.py
> +            otype: The type of the object we're tagging.
```suggestion
            git_object_type: The type of the object we're tagging.
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/argparser.py
> +        help=("Tag to use for release"),
```suggestion
        help="Tag to use for release",
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/argparser.py
> +        help=("Description for the Release. Can be formatted in Markdown."),
```suggestion
        help="Description for the Release. Can be formatted in Markdown.",
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/argparser.py
> +        "-tc", "--target-commitish", default=None, help="??"
```suggestion
        "-tc", "--target-commitish", default=None, help="Git reference to use for the release"
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/argparser.py
> +        help=("Tag name to use"),
```suggestion
        help="Tag name to use",
```

2022-10-17 05:54 UTC, bjoernricks commented on pontos/github/argparser.py
> +        help=("The type of the object we're taggin"),
```suggestion
        help="The type of the object to be tagged",
```

2022-10-19 07:02 UTC, bjoernricks approved these changes

2022-10-19 07:04 UTC, merged