Fix typing of modules in pontos/version
greenbone/pontos pull request #537
Opened 2022-12-21 12:05 UTC by Tacire

**What**:

Fix: Typing of modules in pontos/version

**Why**:

To prepare pontos for automatic mypy-checks in the future

**How**:

Fixed occuring mypy errors:
`poetry run mypy pontos/version`

**Checklist**:

- [X] Tests
- [X] Conventional commit message
- [ ] Documentation

2022-12-23 06:46 UTC, bjoernricks requested changes

2022-12-23 06:46 UTC, bjoernricks commented on pontos/version/cmake.py
> +        self.project_file_path: Path
This should better be typed in the parent class VersionCommand
```suggestion
```

2022-12-23 06:46 UTC, bjoernricks commented on pontos/version/cmake.py
> +    def _tokenize(  # type: ignore
Just for curiosity why is `type: ignore` necessary here?

2022-12-23 06:46 UTC, bjoernricks commented on pontos/version/javascript.py
> +        self.project_file_path: Path
```suggestion
```

2022-12-23 06:46 UTC, bjoernricks commented on pontos/version/python.py
> +        pontos_version_settings: tomlkit.items.Table = (  # fmt: skip
Why is  `fmt: skip` necessary here and which tool uses this comment?

2022-12-23 06:46 UTC, bjoernricks commented on pontos/version/python.py
> +        self.project_file_path: Path
I really think this belongs to the parent class where the variables are initialized.
```suggestion
```

2022-12-23 10:38 UTC, Tacire commented on pontos/version/cmake.py
> +        self.project_file_path: Path
it can't since `project_file_path` is usually `Optional(Path | None)`. But early on in the constructor we check the `None` case and set a Path. That means only in this subclass `project_file_path` is welldefined to be a `Path`

2022-12-23 10:47 UTC, Tacire commented on pontos/version/cmake.py
> +    def _tokenize(  # type: ignore
this has to do with the Generator. Mypy doesn't like implied return statements so that's an error (implied is here `return None`). If i explicitly `return None` there is a conflict between the return value (`Tuple(int,str,str)` and `None`).
So as far as i can see the only way to correctly type this is to return a final Tuple (which wouldn't be part of the Iterable, but necessary to satisfy mypy). Since i believe the readability might suffer from that i decided to simply ignore the typing in `_tokenize()`. I'm open to better solutions if you have any in mind

2022-12-23 10:47 UTC, Tacire commented on pontos/version/javascript.py
> +        self.project_file_path: Path
See above for my explanation

2022-12-23 10:50 UTC, Tacire commented on pontos/version/python.py
> +        pontos_version_settings: tomlkit.items.Table = (  # fmt: skip
Since i added another comment to ignore typing, black escalates the formating like that:
```
        pontos_version_settings: tomlkit.items.Table = self.pyproject_toml[
            "tool"
        ]["pontos"][
            "version"
        ]  # type: ignore

```
I find that quite unreadable so i decided to skip the line in black

2022-12-23 10:51 UTC, Tacire commented on pontos/version/python.py
> +        self.project_file_path: Path
See above for my explanation

2022-12-29 12:19 UTC, Tacire commented on pontos/version/cmake.py
> +        self.project_file_path: Path
I comited an alternative to the typing. The typing of self.project_file_path is defined in VersionCommand. Any time we check self.project_file_path we get that typing (`Path | None`) even if we initialize VersionCommand with an `Path`.The only way to update that is with `self.project_file_path: Path`.

In my Tests even with this init
```
super().__init__(
            version_file_path = Path.cwd(),
            project_file_path= Path.cwd(),
)
```
version_file_path will still be of the type: `Optional[Path]`

This is an syntax error:
```
super().__init__(
            version_file_path: Path = Path.cwd(),
            project_file_path: Path= Path.cwd(),
)
```

So our Options are to make the Paths mandatory(like i started in my last commit), to remove the call of self.project_file_path, or to type it like i did in my first commit. Let me know what you think

2023-01-26 15:05 UTC, closed without merging