Fix: typing in pontos/changelog
greenbone/pontos pull request #671
Opened 2023-03-06 15:47 UTC by Tacire

## What

Fixed some typing errors. Testet with `poetry run mypy pontos/changelog`

## Why

To prepare pontos for posible automatic typing checks in the future

## References

DEVOPS-354

## Checklist

- [X] Tests

2023-03-07 07:11 UTC, bjoernricks requested changes
I still don't get why so many type ignore statements are necessary, even when you added the type for example `spec: ModuleSpec`.

2023-03-07 07:11 UTC, bjoernricks commented on pontos/changelog/main.py
> +def parse_args(args: Optional[Sequence[str]] = None) -> ArgumentParser:
From looking at the function the return type seems to be wrong to me. Should be `Namespace` from `argparse`.
```suggestion
def parse_args(args: Optional[Sequence[str]] = None) -> Namespace:
```

2023-03-07 07:11 UTC, bjoernricks commented on pontos/changelog/main.py
> +    parsed_args = parse_args(args)  # type: ignore
Maybe this is not necessary anymore when the return type is adjusted?

2023-03-07 07:11 UTC, bjoernricks commented on pontos/version/cmake.py
> +        self._current_version = str(new_version)
I really don't think this is correct. IMHO it should be a `Version` instance.

2023-03-07 07:11 UTC, bjoernricks commented on pontos/version/commands.py
> +__COMMANDS: Tuple[Type[VersionCommand]] = (  # type: ignore
Why is this necessary? It has clearly a type.

2023-03-07 07:11 UTC, bjoernricks commented on pontos/version/parser.py
> +        return "current"
Shouldn't be necessary at all.

2023-03-07 11:12 UTC, Tacire commented on pontos/version/commands.py
> +__COMMANDS: Tuple[Type[VersionCommand]] = (  # type: ignore
mypy doesn't recognize e.g. `CMakeVersionCommand` as of Type `VersionCommand` and marks this as error. Maybe i could type them also? But i don't think that this would improve readability of this code

2023-03-07 11:15 UTC, Tacire commented on pontos/version/parser.py
> +        return "current"
sadly it is, since `version` is of type `str`, mypy, for whatever reason, doesn't accept that in this case it's `Literal["current"]`. So it marks that line as typing error

2023-03-07 11:20 UTC, Tacire commented on pontos/version/cmake.py
> +        self._current_version = str(new_version)
i checked the code and `self._current_version` is consequently used like a string (for example check line 114). But i agree that it should be a `Version`, so if you want i can change its usage that way

2023-03-07 11:25 UTC, Tacire commented on pontos/changelog/main.py
> +def parse_args(args: Optional[Sequence[str]] = None) -> ArgumentParser:
Thanks, saved a lot of `#type: ignore` now :D

2023-03-07 11:26 UTC, Tacire commented on pontos/changelog/main.py
> +    parsed_args = parse_args(args)  # type: ignore
Did work :+1:

2023-03-16 15:06 UTC, Tacire commented
Deleted because of updated PR https://github.com/greenbone/pontos/pull/682

2023-03-16 15:06 UTC, closed without merging