Semver support
greenbone/pontos pull request #675
Opened 2023-03-10 13:29 UTC by bjoernricks

## What

Support [SemVer](https://semver.org/) for versioning.

This PR introduces flexible versioning schemes and implements PEP 440 and SemVer. It also allows to convert versions from and to different versioning schemes. This is used for Python based projects where PEP 440 versions are always loaded and written.

## Why

We require SemVer for versioning of Helm Charts.

## References

DEVOPS-598

## Checklist

- [ ] Tests

2023-03-13 19:26 UTC, y0urself requested changes

2023-03-13 19:26 UTC, y0urself commented on pontos/version/main.py
> +            sys.exit(VersionExitCode.NEXT_VERSION_ERROR)
While writing tests, I don't think this is reachable code, there are no possible exceptions, that can be thrown. The only way this could be "generated", would be by passing a faulty `current_version`, which will already be caught within `get_current_version`.

2023-03-14 08:37 UTC, pascalholthaus approved these changes

2023-03-14 08:39 UTC, y0urself approved these changes

2023-03-14 08:39 UTC, merged